/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threesgame;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Random;
import java.util.Timer;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author lunac
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    GrilleDeJeu grille;
    int nbCoups=0;
    Timer chrono = new Timer();
    
    public void InitialiserPartie(){
        
        grille.GrilleDepart();
        
    }
    public FenetrePrincipale() {
        
        initComponents();
        //CelluleChiffree cellule;
        
        int rand;
        this.grille= new GrilleDeJeu();
        InitialiserPartie();
        Random random = new Random();
        rand=random.nextInt(4) + 1;
        GrilleJeu.setLayout(new GridLayout(4, 4));
        
        for (int i=0; i < 4; i++) {
            for (int j=0; j < 4; j++ ) {
            CelluleGraphique bouton_cellule = new CelluleGraphique(grille.matriceCellules[i][j]);
            if(j==rand){
                bouton_cellule.celluleChiffreeAssociee.valeur=random.nextInt(3) + 1;
                if (bouton_cellule.celluleChiffreeAssociee.valeur!=0){
                    bouton_cellule.setText(""+bouton_cellule.celluleChiffreeAssociee.valeur);
                    rand=random.nextInt(4)+1;
                }
                
            }
            if (i==rand){
                bouton_cellule.celluleChiffreeAssociee.valeur=random.nextInt(3) + 1;
                if (bouton_cellule.celluleChiffreeAssociee.valeur!=0){
                    bouton_cellule.setText(""+ bouton_cellule.celluleChiffreeAssociee.valeur);
                    rand=random.nextInt(4)+1; 
                }
            }
            GrilleJeu.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }        
        }
        
        // association des jButtons aux touches flêches du clavier
        bindButtonToKey(leftButton, KeyEvent.VK_LEFT);
        bindButtonToKey(rightButton, KeyEvent.VK_RIGHT);
        bindButtonToKey(upButton, KeyEvent.VK_UP);
        bindButtonToKey(downButton, KeyEvent.VK_DOWN);
        
    }
    
    private void bindButtonToKey(JButton button, int keyCode) {
        
        InputMap inputMap = button.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = button.getActionMap();

        String key = "key" + keyCode;

        inputMap.put(KeyStroke.getKeyStroke(keyCode, 0, false), key);
        actionMap.put(key, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                button.doClick();
            }
        });
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        GrilleJeu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rightButton = new javax.swing.JButton();
        reglages = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GrilleJeu.setBackground(new java.awt.Color(102, 204, 255));
        GrilleJeu.setLayout(new java.awt.GridLayout(1, 0));

        rightButton.setBackground(new java.awt.Color(102, 204, 255));
        rightButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rightButton.setText("-->");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(rightButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        reglages.setBackground(new java.awt.Color(255, 153, 204));
        reglages.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        reglages.setText("Accéder aux réglages");
        reglages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglagesActionPerformed(evt);
            }
        });

        leftButton.setBackground(new java.awt.Color(102, 204, 255));
        leftButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leftButton.setText("<--");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        upButton.setBackground(new java.awt.Color(102, 204, 255));
        upButton.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        upButton.setText("up");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        downButton.setBackground(new java.awt.Color(102, 204, 255));
        downButton.setFont(new java.awt.Font("Bauhaus 93", 0, 12)); // NOI18N
        downButton.setText("down");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(downButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reglages, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GrilleJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(upButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GrilleJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(leftButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downButton)
                .addGap(32, 32, 32)
                .addComponent(reglages, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        // TODO add your handling code here:
        
        nbCoups+=1;
        this.grille.deplacementG();
        GrilleJeu.repaint();     
        if (grille.VerifGrille()==true){
            
            FenetreDefaite f=new FenetreDefaite();
            f.setVisible(true);
            this.dispose();
        }
        
        System.out.println(this.grille);
        System.out.println(nbCoups);
        
    }//GEN-LAST:event_leftButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        // TODO add your handling code here:
        nbCoups+=1;
        this.grille.deplacementDown();
        GrilleJeu.repaint();
        if (grille.VerifGrille()==true){
            
            FenetreDefaite f=new FenetreDefaite();
            f.setVisible(true);
            this.dispose();
            
        }
        
        System.out.println(this.grille);
    }//GEN-LAST:event_downButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        // TODO add your handling code here:
        nbCoups+=1;
        this.grille.deplacementUp();
        GrilleJeu.repaint();
        if (grille.VerifGrille()==true){
              
            FenetreDefaite f=new FenetreDefaite();
            f.setVisible(true);
            this.dispose(); 
        } 
        
        
        System.out.println(this.grille);
    }//GEN-LAST:event_upButtonActionPerformed

    private void reglagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglagesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reglagesActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
        nbCoups+=1;
        this.grille.deplacementD();
        GrilleJeu.repaint();
        if (grille.VerifGrille()==true){
            
            FenetreDefaite f=new FenetreDefaite();
            f.setVisible(true);
            this.dispose();
        }
        

        System.out.println(this.grille);
    }//GEN-LAST:event_rightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GrilleJeu;
    private javax.swing.JButton downButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton reglages;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
